/* Automatically @generated by tree-sitter v0.25.4 (726dcd1e872149d95de581589fc408fb8ea9cb0b) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 150
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 81
#define ALIAS_COUNT 0
#define TOKEN_COUNT 40
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_PERCENT = 1,
  anon_sym_SEMI = 2,
  anon_sym_pkg = 3,
  anon_sym_DOT = 4,
  anon_sym_use = 5,
  anon_sym_as = 6,
  anon_sym_def = 7,
  anon_sym_LPAREN = 8,
  anon_sym_COMMA = 9,
  anon_sym_RPAREN = 10,
  anon_sym_var = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  anon_sym_return = 16,
  anon_sym_BANG = 17,
  anon_sym_PLUS = 18,
  anon_sym_DASH = 19,
  anon_sym_STAR = 20,
  anon_sym_SLASH = 21,
  anon_sym_EQ_EQ = 22,
  anon_sym_BANG_EQ = 23,
  anon_sym_EQ = 24,
  anon_sym_global = 25,
  anon_sym_ext = 26,
  anon_sym_const = 27,
  anon_sym_AT = 28,
  anon_sym_DQUOTE = 29,
  anon_sym_SQUOTE = 30,
  aux_sym_char_token1 = 31,
  sym_string_content = 32,
  sym_escape_sequence = 33,
  sym_comment = 34,
  sym_identifier = 35,
  sym_integer = 36,
  sym_float = 37,
  sym_double = 38,
  sym_boolean = 39,
  sym_source_file = 40,
  sym_linker_option = 41,
  sym_pkg = 42,
  sym_path = 43,
  sym_use = 44,
  sym_statement = 45,
  sym_def = 46,
  sym_def_name = 47,
  sym_def_parameters = 48,
  sym_parameter = 49,
  sym_type = 50,
  sym_def_body = 51,
  sym_def_statement = 52,
  sym_return = 53,
  sym_expr = 54,
  sym_unary = 55,
  sym_binary = 56,
  sym_term = 57,
  sym_call = 58,
  sym_call_arguments = 59,
  sym_argument = 60,
  sym_var = 61,
  sym_global = 62,
  sym_ext = 63,
  sym_method = 64,
  sym_const = 65,
  sym_platform = 66,
  sym_reassign = 67,
  sym_string = 68,
  sym_char = 69,
  aux_sym_source_file_repeat1 = 70,
  aux_sym_source_file_repeat2 = 71,
  aux_sym_source_file_repeat3 = 72,
  aux_sym_linker_option_repeat1 = 73,
  aux_sym_path_repeat1 = 74,
  aux_sym_def_parameters_repeat1 = 75,
  aux_sym_type_repeat1 = 76,
  aux_sym_def_body_repeat1 = 77,
  aux_sym_return_repeat1 = 78,
  aux_sym_call_arguments_repeat1 = 79,
  aux_sym_string_repeat1 = 80,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PERCENT] = "%",
  [anon_sym_SEMI] = ";",
  [anon_sym_pkg] = "pkg",
  [anon_sym_DOT] = ".",
  [anon_sym_use] = "use",
  [anon_sym_as] = "as",
  [anon_sym_def] = "def",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_var] = "var",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_return] = "return",
  [anon_sym_BANG] = "!",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_EQ] = "=",
  [anon_sym_global] = "global",
  [anon_sym_ext] = "ext",
  [anon_sym_const] = "const",
  [anon_sym_AT] = "@",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_char_token1] = "char_token1",
  [sym_string_content] = "string_content",
  [sym_escape_sequence] = "escape_sequence",
  [sym_comment] = "comment",
  [sym_identifier] = "identifier",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_double] = "double",
  [sym_boolean] = "boolean",
  [sym_source_file] = "source_file",
  [sym_linker_option] = "linker_option",
  [sym_pkg] = "pkg",
  [sym_path] = "path",
  [sym_use] = "use",
  [sym_statement] = "statement",
  [sym_def] = "def",
  [sym_def_name] = "def_name",
  [sym_def_parameters] = "def_parameters",
  [sym_parameter] = "parameter",
  [sym_type] = "type",
  [sym_def_body] = "def_body",
  [sym_def_statement] = "def_statement",
  [sym_return] = "return",
  [sym_expr] = "expr",
  [sym_unary] = "unary",
  [sym_binary] = "binary",
  [sym_term] = "term",
  [sym_call] = "call",
  [sym_call_arguments] = "call_arguments",
  [sym_argument] = "argument",
  [sym_var] = "var",
  [sym_global] = "global",
  [sym_ext] = "ext",
  [sym_method] = "method",
  [sym_const] = "const",
  [sym_platform] = "platform",
  [sym_reassign] = "reassign",
  [sym_string] = "string",
  [sym_char] = "char",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_source_file_repeat3] = "source_file_repeat3",
  [aux_sym_linker_option_repeat1] = "linker_option_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
  [aux_sym_def_parameters_repeat1] = "def_parameters_repeat1",
  [aux_sym_type_repeat1] = "type_repeat1",
  [aux_sym_def_body_repeat1] = "def_body_repeat1",
  [aux_sym_return_repeat1] = "return_repeat1",
  [aux_sym_call_arguments_repeat1] = "call_arguments_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_pkg] = anon_sym_pkg,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_global] = anon_sym_global,
  [anon_sym_ext] = anon_sym_ext,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_char_token1] = aux_sym_char_token1,
  [sym_string_content] = sym_string_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_comment] = sym_comment,
  [sym_identifier] = sym_identifier,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_double] = sym_double,
  [sym_boolean] = sym_boolean,
  [sym_source_file] = sym_source_file,
  [sym_linker_option] = sym_linker_option,
  [sym_pkg] = sym_pkg,
  [sym_path] = sym_path,
  [sym_use] = sym_use,
  [sym_statement] = sym_statement,
  [sym_def] = sym_def,
  [sym_def_name] = sym_def_name,
  [sym_def_parameters] = sym_def_parameters,
  [sym_parameter] = sym_parameter,
  [sym_type] = sym_type,
  [sym_def_body] = sym_def_body,
  [sym_def_statement] = sym_def_statement,
  [sym_return] = sym_return,
  [sym_expr] = sym_expr,
  [sym_unary] = sym_unary,
  [sym_binary] = sym_binary,
  [sym_term] = sym_term,
  [sym_call] = sym_call,
  [sym_call_arguments] = sym_call_arguments,
  [sym_argument] = sym_argument,
  [sym_var] = sym_var,
  [sym_global] = sym_global,
  [sym_ext] = sym_ext,
  [sym_method] = sym_method,
  [sym_const] = sym_const,
  [sym_platform] = sym_platform,
  [sym_reassign] = sym_reassign,
  [sym_string] = sym_string,
  [sym_char] = sym_char,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_source_file_repeat3] = aux_sym_source_file_repeat3,
  [aux_sym_linker_option_repeat1] = aux_sym_linker_option_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
  [aux_sym_def_parameters_repeat1] = aux_sym_def_parameters_repeat1,
  [aux_sym_type_repeat1] = aux_sym_type_repeat1,
  [aux_sym_def_body_repeat1] = aux_sym_def_body_repeat1,
  [aux_sym_return_repeat1] = aux_sym_return_repeat1,
  [aux_sym_call_arguments_repeat1] = aux_sym_call_arguments_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pkg] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_global] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ext] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_char_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_double] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_linker_option] = {
    .visible = true,
    .named = true,
  },
  [sym_pkg] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_use] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_def] = {
    .visible = true,
    .named = true,
  },
  [sym_def_name] = {
    .visible = true,
    .named = true,
  },
  [sym_def_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_def_body] = {
    .visible = true,
    .named = true,
  },
  [sym_def_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_unary] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_call_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_var] = {
    .visible = true,
    .named = true,
  },
  [sym_global] = {
    .visible = true,
    .named = true,
  },
  [sym_ext] = {
    .visible = true,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_const] = {
    .visible = true,
    .named = true,
  },
  [sym_platform] = {
    .visible = true,
    .named = true,
  },
  [sym_reassign] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_linker_option_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_def_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_def_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_return_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(51);
      ADVANCE_MAP(
        '!', 72,
        '"', 85,
        '#', 94,
        '%', 52,
        '\'', 86,
        '(', 60,
        ')', 62,
        '*', 75,
        '+', 73,
        ',', 61,
        '-', 74,
        '.', 56,
        '/', 76,
        '0', 109,
        ';', 53,
        '=', 80,
        '@', 84,
        '[', 67,
        '\\', 37,
        ']', 68,
        'a', 30,
        'c', 25,
        'd', 13,
        'e', 40,
        'f', 9,
        'g', 21,
        'p', 19,
        'r', 16,
        't', 27,
        'u', 31,
        'v', 10,
        '{', 65,
        '}', 66,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(110);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 71,
        '"', 85,
        '\'', 86,
        '(', 60,
        ')', 62,
        '*', 75,
        '+', 73,
        ',', 61,
        '-', 74,
        '.', 43,
        '/', 76,
        '0', 109,
        ';', 53,
        '=', 79,
        '[', 67,
        'f', 95,
        't', 101,
        '{', 65,
        '}', 66,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(110);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 6,
        '#', 94,
        '(', 60,
        ')', 62,
        ',', 61,
        '.', 55,
        ';', 53,
        '=', 7,
        'r', 98,
        'v', 96,
        '}', 66,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == ')') ADVANCE(62);
      if (lookahead == ',') ADVANCE(61);
      if (lookahead == ';') ADVANCE(53);
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == '@') ADVANCE(84);
      if (lookahead == 'a') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(85);
      if (lookahead == '\\') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(60);
      if (lookahead == ')') ADVANCE(62);
      if (lookahead == '.') ADVANCE(55);
      if (lookahead == '=') ADVANCE(79);
      if (lookahead == 'v') ADVANCE(96);
      if (lookahead == '{') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(78);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(77);
      END_STATE();
    case 8:
      if (lookahead == '\\') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(87);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(116);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 17:
      if (lookahead == 'f') ADVANCE(59);
      END_STATE();
    case 18:
      if (lookahead == 'g') ADVANCE(54);
      END_STATE();
    case 19:
      if (lookahead == 'k') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(81);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(63);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(58);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(82);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(83);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 37:
      ADVANCE_MAP(
        'u', 50,
        'x', 48,
        '"', 91,
        '\\', 91,
        'b', 91,
        'f', 91,
        'n', 91,
        'r', 91,
        't', 91,
        'v', 91,
      );
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(93);
      END_STATE();
    case 38:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 40:
      if (lookahead == 'x') ADVANCE(34);
      END_STATE();
    case 41:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(111);
      END_STATE();
    case 42:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      END_STATE();
    case 43:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 44:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(111);
      END_STATE();
    case 45:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      END_STATE();
    case 46:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(91);
      END_STATE();
    case 47:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(112);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(46);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(48);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(49);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_pkg);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_var);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(78);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(77);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_global);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_ext);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_char_token1);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_char_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(87);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_string_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(90);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(91);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(92);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(114);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(41);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(110);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(114);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(110);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(111);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(112);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_float);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_double);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_double);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_boolean);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 4},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 5},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 8},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 1},
  [125] = {.lex_state = 1},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 1},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 1},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 1},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 1},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 1},
  [137] = {.lex_state = 1},
  [138] = {.lex_state = 1},
  [139] = {.lex_state = 1},
  [140] = {.lex_state = 1},
  [141] = {.lex_state = 1},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 1},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 1},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_pkg] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_global] = ACTIONS(1),
    [anon_sym_ext] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_double] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(135),
    [sym_linker_option] = STATE(43),
    [sym_pkg] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(43),
    [anon_sym_PERCENT] = ACTIONS(3),
    [anon_sym_pkg] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_float,
    STATE(45), 1,
      sym_term,
    STATE(79), 1,
      sym_argument,
    STATE(114), 1,
      sym_def_name,
    STATE(121), 1,
      sym_expr,
    STATE(93), 2,
      sym_unary,
      sym_binary,
    ACTIONS(19), 3,
      sym_integer,
      sym_double,
      sym_boolean,
    STATE(44), 3,
      sym_call,
      sym_string,
      sym_char,
    ACTIONS(11), 5,
      anon_sym_BANG,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [52] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_float,
    STATE(45), 1,
      sym_term,
    STATE(114), 1,
      sym_def_name,
    STATE(117), 1,
      sym_argument,
    STATE(121), 1,
      sym_expr,
    STATE(93), 2,
      sym_unary,
      sym_binary,
    ACTIONS(19), 3,
      sym_integer,
      sym_double,
      sym_boolean,
    STATE(44), 3,
      sym_call,
      sym_string,
      sym_char,
    ACTIONS(11), 5,
      anon_sym_BANG,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [101] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_float,
    ACTIONS(23), 1,
      anon_sym_SEMI,
    STATE(45), 1,
      sym_term,
    STATE(90), 1,
      sym_expr,
    STATE(114), 1,
      sym_def_name,
    STATE(93), 2,
      sym_unary,
      sym_binary,
    ACTIONS(19), 3,
      sym_integer,
      sym_double,
      sym_boolean,
    STATE(44), 3,
      sym_call,
      sym_string,
      sym_char,
    ACTIONS(11), 5,
      anon_sym_BANG,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [150] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_float,
    STATE(45), 1,
      sym_term,
    STATE(114), 1,
      sym_def_name,
    STATE(133), 1,
      sym_expr,
    STATE(93), 2,
      sym_unary,
      sym_binary,
    ACTIONS(19), 3,
      sym_integer,
      sym_double,
      sym_boolean,
    STATE(44), 3,
      sym_call,
      sym_string,
      sym_char,
    ACTIONS(11), 5,
      anon_sym_BANG,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [196] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_float,
    STATE(45), 1,
      sym_term,
    STATE(114), 1,
      sym_def_name,
    STATE(115), 1,
      sym_expr,
    STATE(93), 2,
      sym_unary,
      sym_binary,
    ACTIONS(19), 3,
      sym_integer,
      sym_double,
      sym_boolean,
    STATE(44), 3,
      sym_call,
      sym_string,
      sym_char,
    ACTIONS(11), 5,
      anon_sym_BANG,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [242] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_float,
    STATE(45), 1,
      sym_term,
    STATE(114), 1,
      sym_def_name,
    STATE(144), 1,
      sym_expr,
    STATE(93), 2,
      sym_unary,
      sym_binary,
    ACTIONS(19), 3,
      sym_integer,
      sym_double,
      sym_boolean,
    STATE(44), 3,
      sym_call,
      sym_string,
      sym_char,
    ACTIONS(11), 5,
      anon_sym_BANG,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [288] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_float,
    STATE(45), 1,
      sym_term,
    STATE(114), 1,
      sym_def_name,
    STATE(148), 1,
      sym_expr,
    STATE(93), 2,
      sym_unary,
      sym_binary,
    ACTIONS(19), 3,
      sym_integer,
      sym_double,
      sym_boolean,
    STATE(44), 3,
      sym_call,
      sym_string,
      sym_char,
    ACTIONS(11), 5,
      anon_sym_BANG,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [334] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_float,
    STATE(45), 1,
      sym_term,
    STATE(114), 1,
      sym_def_name,
    STATE(123), 1,
      sym_expr,
    STATE(93), 2,
      sym_unary,
      sym_binary,
    ACTIONS(19), 3,
      sym_integer,
      sym_double,
      sym_boolean,
    STATE(44), 3,
      sym_call,
      sym_string,
      sym_char,
    ACTIONS(11), 5,
      anon_sym_BANG,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [380] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_float,
    STATE(45), 1,
      sym_term,
    STATE(114), 1,
      sym_def_name,
    STATE(130), 1,
      sym_expr,
    STATE(93), 2,
      sym_unary,
      sym_binary,
    ACTIONS(19), 3,
      sym_integer,
      sym_double,
      sym_boolean,
    STATE(44), 3,
      sym_call,
      sym_string,
      sym_char,
    ACTIONS(11), 5,
      anon_sym_BANG,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [426] = 10,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_use,
    ACTIONS(29), 1,
      anon_sym_def,
    ACTIONS(31), 1,
      anon_sym_global,
    ACTIONS(33), 1,
      anon_sym_ext,
    ACTIONS(35), 1,
      anon_sym_const,
    ACTIONS(37), 1,
      sym_comment,
    STATE(12), 2,
      sym_use,
      aux_sym_source_file_repeat2,
    STATE(17), 2,
      sym_statement,
      aux_sym_source_file_repeat3,
    STATE(35), 4,
      sym_def,
      sym_global,
      sym_ext,
      sym_const,
  [462] = 10,
    ACTIONS(27), 1,
      anon_sym_use,
    ACTIONS(29), 1,
      anon_sym_def,
    ACTIONS(31), 1,
      anon_sym_global,
    ACTIONS(33), 1,
      anon_sym_ext,
    ACTIONS(35), 1,
      anon_sym_const,
    ACTIONS(37), 1,
      sym_comment,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    STATE(20), 2,
      sym_statement,
      aux_sym_source_file_repeat3,
    STATE(24), 2,
      sym_use,
      aux_sym_source_file_repeat2,
    STATE(35), 4,
      sym_def,
      sym_global,
      sym_ext,
      sym_const,
  [498] = 10,
    ACTIONS(27), 1,
      anon_sym_use,
    ACTIONS(29), 1,
      anon_sym_def,
    ACTIONS(31), 1,
      anon_sym_global,
    ACTIONS(33), 1,
      anon_sym_ext,
    ACTIONS(35), 1,
      anon_sym_const,
    ACTIONS(37), 1,
      sym_comment,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    STATE(14), 2,
      sym_use,
      aux_sym_source_file_repeat2,
    STATE(20), 2,
      sym_statement,
      aux_sym_source_file_repeat3,
    STATE(35), 4,
      sym_def,
      sym_global,
      sym_ext,
      sym_const,
  [534] = 10,
    ACTIONS(27), 1,
      anon_sym_use,
    ACTIONS(29), 1,
      anon_sym_def,
    ACTIONS(31), 1,
      anon_sym_global,
    ACTIONS(33), 1,
      anon_sym_ext,
    ACTIONS(35), 1,
      anon_sym_const,
    ACTIONS(37), 1,
      sym_comment,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(18), 2,
      sym_statement,
      aux_sym_source_file_repeat3,
    STATE(24), 2,
      sym_use,
      aux_sym_source_file_repeat2,
    STATE(35), 4,
      sym_def,
      sym_global,
      sym_ext,
      sym_const,
  [570] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_float,
    STATE(80), 1,
      sym_term,
    STATE(114), 1,
      sym_def_name,
    ACTIONS(19), 3,
      sym_integer,
      sym_double,
      sym_boolean,
    STATE(44), 3,
      sym_call,
      sym_string,
      sym_char,
  [602] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_float,
    STATE(76), 1,
      sym_term,
    STATE(114), 1,
      sym_def_name,
    ACTIONS(19), 3,
      sym_integer,
      sym_double,
      sym_boolean,
    STATE(44), 3,
      sym_call,
      sym_string,
      sym_char,
  [634] = 8,
    ACTIONS(29), 1,
      anon_sym_def,
    ACTIONS(31), 1,
      anon_sym_global,
    ACTIONS(33), 1,
      anon_sym_ext,
    ACTIONS(35), 1,
      anon_sym_const,
    ACTIONS(37), 1,
      sym_comment,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    STATE(19), 2,
      sym_statement,
      aux_sym_source_file_repeat3,
    STATE(35), 4,
      sym_def,
      sym_global,
      sym_ext,
      sym_const,
  [663] = 8,
    ACTIONS(29), 1,
      anon_sym_def,
    ACTIONS(31), 1,
      anon_sym_global,
    ACTIONS(33), 1,
      anon_sym_ext,
    ACTIONS(35), 1,
      anon_sym_const,
    ACTIONS(37), 1,
      sym_comment,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    STATE(19), 2,
      sym_statement,
      aux_sym_source_file_repeat3,
    STATE(35), 4,
      sym_def,
      sym_global,
      sym_ext,
      sym_const,
  [692] = 8,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      anon_sym_def,
    ACTIONS(50), 1,
      anon_sym_global,
    ACTIONS(53), 1,
      anon_sym_ext,
    ACTIONS(56), 1,
      anon_sym_const,
    ACTIONS(59), 1,
      sym_comment,
    STATE(19), 2,
      sym_statement,
      aux_sym_source_file_repeat3,
    STATE(35), 4,
      sym_def,
      sym_global,
      sym_ext,
      sym_const,
  [721] = 8,
    ACTIONS(29), 1,
      anon_sym_def,
    ACTIONS(31), 1,
      anon_sym_global,
    ACTIONS(33), 1,
      anon_sym_ext,
    ACTIONS(35), 1,
      anon_sym_const,
    ACTIONS(37), 1,
      sym_comment,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(19), 2,
      sym_statement,
      aux_sym_source_file_repeat3,
    STATE(35), 4,
      sym_def,
      sym_global,
      sym_ext,
      sym_const,
  [750] = 9,
    ACTIONS(62), 1,
      anon_sym_var,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    ACTIONS(67), 1,
      anon_sym_return,
    ACTIONS(70), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_identifier,
    STATE(114), 1,
      sym_def_name,
    STATE(122), 1,
      sym_call,
    STATE(21), 2,
      sym_def_statement,
      aux_sym_def_body_repeat1,
    STATE(47), 3,
      sym_return,
      sym_var,
      sym_reassign,
  [781] = 9,
    ACTIONS(76), 1,
      anon_sym_var,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    ACTIONS(80), 1,
      anon_sym_return,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(114), 1,
      sym_def_name,
    STATE(122), 1,
      sym_call,
    STATE(21), 2,
      sym_def_statement,
      aux_sym_def_body_repeat1,
    STATE(47), 3,
      sym_return,
      sym_var,
      sym_reassign,
  [812] = 9,
    ACTIONS(76), 1,
      anon_sym_var,
    ACTIONS(80), 1,
      anon_sym_return,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(84), 1,
      sym_identifier,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    STATE(114), 1,
      sym_def_name,
    STATE(122), 1,
      sym_call,
    STATE(22), 2,
      sym_def_statement,
      aux_sym_def_body_repeat1,
    STATE(47), 3,
      sym_return,
      sym_var,
      sym_reassign,
  [843] = 3,
    ACTIONS(90), 1,
      anon_sym_use,
    STATE(24), 2,
      sym_use,
      aux_sym_source_file_repeat2,
    ACTIONS(88), 6,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_global,
      anon_sym_ext,
      anon_sym_const,
      sym_comment,
  [859] = 1,
    ACTIONS(93), 7,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_def,
      anon_sym_global,
      anon_sym_ext,
      anon_sym_const,
      sym_comment,
  [869] = 1,
    ACTIONS(95), 7,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_def,
      anon_sym_global,
      anon_sym_ext,
      anon_sym_const,
      sym_comment,
  [879] = 3,
    ACTIONS(99), 1,
      anon_sym_DOT,
    ACTIONS(101), 1,
      anon_sym_LPAREN,
    ACTIONS(97), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [893] = 1,
    ACTIONS(103), 7,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_def,
      anon_sym_global,
      anon_sym_ext,
      anon_sym_const,
      sym_comment,
  [903] = 1,
    ACTIONS(105), 7,
      anon_sym_SEMI,
      anon_sym_as,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AT,
  [913] = 1,
    ACTIONS(107), 7,
      anon_sym_SEMI,
      anon_sym_as,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AT,
  [923] = 1,
    ACTIONS(109), 6,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_global,
      anon_sym_ext,
      anon_sym_const,
      sym_comment,
  [932] = 1,
    ACTIONS(111), 6,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_global,
      anon_sym_ext,
      anon_sym_const,
      sym_comment,
  [941] = 1,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_global,
      anon_sym_ext,
      anon_sym_const,
      sym_comment,
  [950] = 1,
    ACTIONS(115), 6,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_global,
      anon_sym_ext,
      anon_sym_const,
      sym_comment,
  [959] = 1,
    ACTIONS(117), 6,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_global,
      anon_sym_ext,
      anon_sym_const,
      sym_comment,
  [968] = 1,
    ACTIONS(119), 6,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_global,
      anon_sym_ext,
      anon_sym_const,
      sym_comment,
  [977] = 4,
    ACTIONS(29), 1,
      anon_sym_def,
    ACTIONS(33), 1,
      anon_sym_ext,
    ACTIONS(35), 1,
      anon_sym_const,
    STATE(34), 3,
      sym_def,
      sym_ext,
      sym_const,
  [992] = 6,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    ACTIONS(123), 1,
      anon_sym_var,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    ACTIONS(127), 1,
      sym_identifier,
    STATE(82), 1,
      sym_parameter,
    STATE(143), 1,
      sym_type,
  [1011] = 1,
    ACTIONS(129), 6,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_global,
      anon_sym_ext,
      anon_sym_const,
      sym_comment,
  [1020] = 1,
    ACTIONS(131), 6,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_global,
      anon_sym_ext,
      anon_sym_const,
      sym_comment,
  [1029] = 3,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    STATE(41), 1,
      aux_sym_type_repeat1,
    ACTIONS(133), 3,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [1041] = 2,
    ACTIONS(140), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(138), 3,
      anon_sym_var,
      anon_sym_return,
      sym_identifier,
  [1051] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_pkg,
    STATE(13), 1,
      sym_pkg,
    STATE(65), 2,
      sym_linker_option,
      aux_sym_source_file_repeat1,
  [1065] = 1,
    ACTIONS(97), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1073] = 2,
    ACTIONS(144), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(142), 3,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1083] = 5,
    ACTIONS(123), 1,
      anon_sym_var,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    ACTIONS(127), 1,
      sym_identifier,
    STATE(103), 1,
      sym_parameter,
    STATE(143), 1,
      sym_type,
  [1099] = 2,
    ACTIONS(148), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(146), 3,
      anon_sym_var,
      anon_sym_return,
      sym_identifier,
  [1109] = 1,
    ACTIONS(150), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1117] = 2,
    ACTIONS(154), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(152), 3,
      anon_sym_var,
      anon_sym_return,
      sym_identifier,
  [1127] = 2,
    ACTIONS(158), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(156), 3,
      anon_sym_var,
      anon_sym_return,
      sym_identifier,
  [1137] = 1,
    ACTIONS(160), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1145] = 1,
    ACTIONS(162), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1153] = 1,
    ACTIONS(164), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1161] = 2,
    ACTIONS(168), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(166), 3,
      anon_sym_var,
      anon_sym_return,
      sym_identifier,
  [1171] = 1,
    ACTIONS(170), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1179] = 2,
    ACTIONS(174), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(172), 3,
      anon_sym_var,
      anon_sym_return,
      sym_identifier,
  [1189] = 2,
    ACTIONS(178), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(176), 3,
      anon_sym_var,
      anon_sym_return,
      sym_identifier,
  [1199] = 2,
    ACTIONS(182), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(180), 3,
      anon_sym_var,
      anon_sym_return,
      sym_identifier,
  [1209] = 1,
    ACTIONS(184), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1217] = 2,
    ACTIONS(188), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(186), 3,
      anon_sym_var,
      anon_sym_return,
      sym_identifier,
  [1227] = 2,
    ACTIONS(192), 2,
      anon_sym_RBRACE,
      sym_comment,
    ACTIONS(190), 3,
      anon_sym_var,
      anon_sym_return,
      sym_identifier,
  [1237] = 3,
    ACTIONS(194), 1,
      anon_sym_SEMI,
    ACTIONS(196), 1,
      anon_sym_AT,
    STATE(62), 2,
      sym_platform,
      aux_sym_linker_option_repeat1,
  [1248] = 4,
    ACTIONS(199), 1,
      anon_sym_DQUOTE,
    ACTIONS(201), 1,
      sym_string_content,
    ACTIONS(203), 1,
      sym_escape_sequence,
    STATE(68), 1,
      aux_sym_string_repeat1,
  [1261] = 4,
    ACTIONS(205), 1,
      anon_sym_DQUOTE,
    ACTIONS(207), 1,
      sym_string_content,
    ACTIONS(210), 1,
      sym_escape_sequence,
    STATE(64), 1,
      aux_sym_string_repeat1,
  [1274] = 3,
    ACTIONS(213), 1,
      anon_sym_PERCENT,
    ACTIONS(216), 1,
      anon_sym_pkg,
    STATE(65), 2,
      sym_linker_option,
      aux_sym_source_file_repeat1,
  [1285] = 3,
    ACTIONS(218), 1,
      anon_sym_SEMI,
    ACTIONS(220), 1,
      anon_sym_AT,
    STATE(70), 2,
      sym_platform,
      aux_sym_linker_option_repeat1,
  [1296] = 1,
    ACTIONS(133), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [1303] = 4,
    ACTIONS(222), 1,
      anon_sym_DQUOTE,
    ACTIONS(224), 1,
      sym_string_content,
    ACTIONS(226), 1,
      sym_escape_sequence,
    STATE(64), 1,
      aux_sym_string_repeat1,
  [1316] = 4,
    ACTIONS(228), 1,
      anon_sym_SEMI,
    ACTIONS(230), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      anon_sym_EQ,
    STATE(72), 1,
      aux_sym_type_repeat1,
  [1329] = 3,
    ACTIONS(220), 1,
      anon_sym_AT,
    ACTIONS(234), 1,
      anon_sym_SEMI,
    STATE(62), 2,
      sym_platform,
      aux_sym_linker_option_repeat1,
  [1340] = 4,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    ACTIONS(236), 1,
      sym_identifier,
    STATE(107), 1,
      sym_method,
    STATE(137), 1,
      sym_type,
  [1353] = 4,
    ACTIONS(230), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_SEMI,
    ACTIONS(240), 1,
      anon_sym_EQ,
    STATE(41), 1,
      aux_sym_type_repeat1,
  [1366] = 3,
    ACTIONS(242), 1,
      anon_sym_SEMI,
    ACTIONS(244), 1,
      anon_sym_DOT,
    STATE(87), 1,
      aux_sym_path_repeat1,
  [1376] = 1,
    ACTIONS(246), 3,
      anon_sym_SEMI,
      anon_sym_as,
      anon_sym_LBRACE,
  [1382] = 3,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    ACTIONS(236), 1,
      sym_identifier,
    STATE(127), 1,
      sym_type,
  [1392] = 1,
    ACTIONS(248), 3,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1398] = 1,
    ACTIONS(250), 3,
      anon_sym_SEMI,
      anon_sym_as,
      anon_sym_LBRACE,
  [1404] = 3,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    ACTIONS(236), 1,
      sym_identifier,
    STATE(136), 1,
      sym_type,
  [1414] = 3,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym_call_arguments_repeat1,
  [1424] = 1,
    ACTIONS(256), 3,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1430] = 3,
    ACTIONS(258), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym_def_parameters_repeat1,
  [1440] = 3,
    ACTIONS(258), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_def_parameters_repeat1,
  [1450] = 3,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    ACTIONS(236), 1,
      sym_identifier,
    STATE(101), 1,
      sym_type,
  [1460] = 3,
    ACTIONS(264), 1,
      anon_sym_SEMI,
    ACTIONS(266), 1,
      anon_sym_COMMA,
    STATE(91), 1,
      aux_sym_return_repeat1,
  [1470] = 1,
    ACTIONS(268), 3,
      anon_sym_SEMI,
      anon_sym_as,
      anon_sym_LBRACE,
  [1476] = 3,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    STATE(94), 1,
      aux_sym_call_arguments_repeat1,
  [1486] = 3,
    ACTIONS(244), 1,
      anon_sym_DOT,
    ACTIONS(272), 1,
      anon_sym_SEMI,
    STATE(95), 1,
      aux_sym_path_repeat1,
  [1496] = 3,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    ACTIONS(277), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym_def_parameters_repeat1,
  [1506] = 3,
    ACTIONS(99), 1,
      anon_sym_DOT,
    ACTIONS(101), 1,
      anon_sym_LPAREN,
    ACTIONS(279), 1,
      anon_sym_EQ,
  [1516] = 3,
    ACTIONS(266), 1,
      anon_sym_COMMA,
    ACTIONS(281), 1,
      anon_sym_SEMI,
    STATE(84), 1,
      aux_sym_return_repeat1,
  [1526] = 3,
    ACTIONS(283), 1,
      anon_sym_SEMI,
    ACTIONS(285), 1,
      anon_sym_COMMA,
    STATE(91), 1,
      aux_sym_return_repeat1,
  [1536] = 3,
    ACTIONS(230), 1,
      anon_sym_COMMA,
    ACTIONS(288), 1,
      anon_sym_RBRACE,
    STATE(97), 1,
      aux_sym_type_repeat1,
  [1546] = 1,
    ACTIONS(142), 3,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1552] = 3,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    STATE(94), 1,
      aux_sym_call_arguments_repeat1,
  [1562] = 3,
    ACTIONS(295), 1,
      anon_sym_SEMI,
    ACTIONS(297), 1,
      anon_sym_DOT,
    STATE(95), 1,
      aux_sym_path_repeat1,
  [1572] = 3,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    ACTIONS(236), 1,
      sym_identifier,
    STATE(141), 1,
      sym_type,
  [1582] = 3,
    ACTIONS(230), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      aux_sym_type_repeat1,
  [1592] = 2,
    ACTIONS(302), 1,
      anon_sym_LBRACK,
    ACTIONS(304), 1,
      sym_identifier,
  [1599] = 1,
    ACTIONS(295), 2,
      anon_sym_SEMI,
      anon_sym_DOT,
  [1604] = 2,
    ACTIONS(99), 1,
      anon_sym_DOT,
    ACTIONS(101), 1,
      anon_sym_LPAREN,
  [1611] = 2,
    ACTIONS(306), 1,
      sym_identifier,
    STATE(104), 1,
      sym_def_name,
  [1618] = 1,
    ACTIONS(308), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1623] = 1,
    ACTIONS(277), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1628] = 2,
    ACTIONS(310), 1,
      anon_sym_LPAREN,
    STATE(116), 1,
      sym_def_parameters,
  [1635] = 2,
    ACTIONS(310), 1,
      anon_sym_LPAREN,
    STATE(119), 1,
      sym_def_parameters,
  [1642] = 2,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    STATE(66), 1,
      sym_string,
  [1649] = 2,
    ACTIONS(312), 1,
      anon_sym_SEMI,
    ACTIONS(314), 1,
      anon_sym_as,
  [1656] = 2,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    STATE(120), 1,
      sym_string,
  [1663] = 1,
    ACTIONS(316), 2,
      anon_sym_PERCENT,
      anon_sym_pkg,
  [1668] = 1,
    ACTIONS(318), 2,
      anon_sym_SEMI,
      anon_sym_AT,
  [1673] = 1,
    ACTIONS(320), 2,
      anon_sym_PERCENT,
      anon_sym_pkg,
  [1678] = 2,
    ACTIONS(322), 1,
      aux_sym_char_token1,
    ACTIONS(324), 1,
      sym_escape_sequence,
  [1685] = 2,
    ACTIONS(326), 1,
      sym_identifier,
    STATE(132), 1,
      sym_path,
  [1692] = 2,
    ACTIONS(328), 1,
      anon_sym_LPAREN,
    STATE(48), 1,
      sym_call_arguments,
  [1699] = 1,
    ACTIONS(283), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1704] = 2,
    ACTIONS(330), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_def_body,
  [1711] = 1,
    ACTIONS(293), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1716] = 1,
    ACTIONS(332), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1721] = 1,
    ACTIONS(334), 2,
      anon_sym_SEMI,
      anon_sym_as,
  [1726] = 2,
    ACTIONS(336), 1,
      anon_sym_SEMI,
    ACTIONS(338), 1,
      anon_sym_as,
  [1733] = 1,
    ACTIONS(340), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1738] = 1,
    ACTIONS(342), 1,
      anon_sym_SEMI,
  [1742] = 1,
    ACTIONS(344), 1,
      anon_sym_RPAREN,
  [1746] = 1,
    ACTIONS(346), 1,
      anon_sym_EQ,
  [1750] = 1,
    ACTIONS(348), 1,
      sym_identifier,
  [1754] = 1,
    ACTIONS(350), 1,
      anon_sym_LPAREN,
  [1758] = 1,
    ACTIONS(352), 1,
      sym_identifier,
  [1762] = 1,
    ACTIONS(354), 1,
      anon_sym_SEMI,
  [1766] = 1,
    ACTIONS(356), 1,
      sym_identifier,
  [1770] = 1,
    ACTIONS(358), 1,
      anon_sym_SEMI,
  [1774] = 1,
    ACTIONS(360), 1,
      sym_identifier,
  [1778] = 1,
    ACTIONS(362), 1,
      anon_sym_SEMI,
  [1782] = 1,
    ACTIONS(364), 1,
      anon_sym_SEMI,
  [1786] = 1,
    ACTIONS(366), 1,
      sym_identifier,
  [1790] = 1,
    ACTIONS(368), 1,
      ts_builtin_sym_end,
  [1794] = 1,
    ACTIONS(370), 1,
      sym_identifier,
  [1798] = 1,
    ACTIONS(372), 1,
      sym_identifier,
  [1802] = 1,
    ACTIONS(374), 1,
      sym_identifier,
  [1806] = 1,
    ACTIONS(376), 1,
      sym_identifier,
  [1810] = 1,
    ACTIONS(378), 1,
      sym_identifier,
  [1814] = 1,
    ACTIONS(380), 1,
      sym_identifier,
  [1818] = 1,
    ACTIONS(288), 1,
      anon_sym_RBRACK,
  [1822] = 1,
    ACTIONS(382), 1,
      sym_identifier,
  [1826] = 1,
    ACTIONS(384), 1,
      anon_sym_SEMI,
  [1830] = 1,
    ACTIONS(386), 1,
      anon_sym_SQUOTE,
  [1834] = 1,
    ACTIONS(388), 1,
      sym_identifier,
  [1838] = 1,
    ACTIONS(390), 1,
      anon_sym_SEMI,
  [1842] = 1,
    ACTIONS(392), 1,
      anon_sym_SEMI,
  [1846] = 1,
    ACTIONS(394), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 52,
  [SMALL_STATE(4)] = 101,
  [SMALL_STATE(5)] = 150,
  [SMALL_STATE(6)] = 196,
  [SMALL_STATE(7)] = 242,
  [SMALL_STATE(8)] = 288,
  [SMALL_STATE(9)] = 334,
  [SMALL_STATE(10)] = 380,
  [SMALL_STATE(11)] = 426,
  [SMALL_STATE(12)] = 462,
  [SMALL_STATE(13)] = 498,
  [SMALL_STATE(14)] = 534,
  [SMALL_STATE(15)] = 570,
  [SMALL_STATE(16)] = 602,
  [SMALL_STATE(17)] = 634,
  [SMALL_STATE(18)] = 663,
  [SMALL_STATE(19)] = 692,
  [SMALL_STATE(20)] = 721,
  [SMALL_STATE(21)] = 750,
  [SMALL_STATE(22)] = 781,
  [SMALL_STATE(23)] = 812,
  [SMALL_STATE(24)] = 843,
  [SMALL_STATE(25)] = 859,
  [SMALL_STATE(26)] = 869,
  [SMALL_STATE(27)] = 879,
  [SMALL_STATE(28)] = 893,
  [SMALL_STATE(29)] = 903,
  [SMALL_STATE(30)] = 913,
  [SMALL_STATE(31)] = 923,
  [SMALL_STATE(32)] = 932,
  [SMALL_STATE(33)] = 941,
  [SMALL_STATE(34)] = 950,
  [SMALL_STATE(35)] = 959,
  [SMALL_STATE(36)] = 968,
  [SMALL_STATE(37)] = 977,
  [SMALL_STATE(38)] = 992,
  [SMALL_STATE(39)] = 1011,
  [SMALL_STATE(40)] = 1020,
  [SMALL_STATE(41)] = 1029,
  [SMALL_STATE(42)] = 1041,
  [SMALL_STATE(43)] = 1051,
  [SMALL_STATE(44)] = 1065,
  [SMALL_STATE(45)] = 1073,
  [SMALL_STATE(46)] = 1083,
  [SMALL_STATE(47)] = 1099,
  [SMALL_STATE(48)] = 1109,
  [SMALL_STATE(49)] = 1117,
  [SMALL_STATE(50)] = 1127,
  [SMALL_STATE(51)] = 1137,
  [SMALL_STATE(52)] = 1145,
  [SMALL_STATE(53)] = 1153,
  [SMALL_STATE(54)] = 1161,
  [SMALL_STATE(55)] = 1171,
  [SMALL_STATE(56)] = 1179,
  [SMALL_STATE(57)] = 1189,
  [SMALL_STATE(58)] = 1199,
  [SMALL_STATE(59)] = 1209,
  [SMALL_STATE(60)] = 1217,
  [SMALL_STATE(61)] = 1227,
  [SMALL_STATE(62)] = 1237,
  [SMALL_STATE(63)] = 1248,
  [SMALL_STATE(64)] = 1261,
  [SMALL_STATE(65)] = 1274,
  [SMALL_STATE(66)] = 1285,
  [SMALL_STATE(67)] = 1296,
  [SMALL_STATE(68)] = 1303,
  [SMALL_STATE(69)] = 1316,
  [SMALL_STATE(70)] = 1329,
  [SMALL_STATE(71)] = 1340,
  [SMALL_STATE(72)] = 1353,
  [SMALL_STATE(73)] = 1366,
  [SMALL_STATE(74)] = 1376,
  [SMALL_STATE(75)] = 1382,
  [SMALL_STATE(76)] = 1392,
  [SMALL_STATE(77)] = 1398,
  [SMALL_STATE(78)] = 1404,
  [SMALL_STATE(79)] = 1414,
  [SMALL_STATE(80)] = 1424,
  [SMALL_STATE(81)] = 1430,
  [SMALL_STATE(82)] = 1440,
  [SMALL_STATE(83)] = 1450,
  [SMALL_STATE(84)] = 1460,
  [SMALL_STATE(85)] = 1470,
  [SMALL_STATE(86)] = 1476,
  [SMALL_STATE(87)] = 1486,
  [SMALL_STATE(88)] = 1496,
  [SMALL_STATE(89)] = 1506,
  [SMALL_STATE(90)] = 1516,
  [SMALL_STATE(91)] = 1526,
  [SMALL_STATE(92)] = 1536,
  [SMALL_STATE(93)] = 1546,
  [SMALL_STATE(94)] = 1552,
  [SMALL_STATE(95)] = 1562,
  [SMALL_STATE(96)] = 1572,
  [SMALL_STATE(97)] = 1582,
  [SMALL_STATE(98)] = 1592,
  [SMALL_STATE(99)] = 1599,
  [SMALL_STATE(100)] = 1604,
  [SMALL_STATE(101)] = 1611,
  [SMALL_STATE(102)] = 1618,
  [SMALL_STATE(103)] = 1623,
  [SMALL_STATE(104)] = 1628,
  [SMALL_STATE(105)] = 1635,
  [SMALL_STATE(106)] = 1642,
  [SMALL_STATE(107)] = 1649,
  [SMALL_STATE(108)] = 1656,
  [SMALL_STATE(109)] = 1663,
  [SMALL_STATE(110)] = 1668,
  [SMALL_STATE(111)] = 1673,
  [SMALL_STATE(112)] = 1678,
  [SMALL_STATE(113)] = 1685,
  [SMALL_STATE(114)] = 1692,
  [SMALL_STATE(115)] = 1699,
  [SMALL_STATE(116)] = 1704,
  [SMALL_STATE(117)] = 1711,
  [SMALL_STATE(118)] = 1716,
  [SMALL_STATE(119)] = 1721,
  [SMALL_STATE(120)] = 1726,
  [SMALL_STATE(121)] = 1733,
  [SMALL_STATE(122)] = 1738,
  [SMALL_STATE(123)] = 1742,
  [SMALL_STATE(124)] = 1746,
  [SMALL_STATE(125)] = 1750,
  [SMALL_STATE(126)] = 1754,
  [SMALL_STATE(127)] = 1758,
  [SMALL_STATE(128)] = 1762,
  [SMALL_STATE(129)] = 1766,
  [SMALL_STATE(130)] = 1770,
  [SMALL_STATE(131)] = 1774,
  [SMALL_STATE(132)] = 1778,
  [SMALL_STATE(133)] = 1782,
  [SMALL_STATE(134)] = 1786,
  [SMALL_STATE(135)] = 1790,
  [SMALL_STATE(136)] = 1794,
  [SMALL_STATE(137)] = 1798,
  [SMALL_STATE(138)] = 1802,
  [SMALL_STATE(139)] = 1806,
  [SMALL_STATE(140)] = 1810,
  [SMALL_STATE(141)] = 1814,
  [SMALL_STATE(142)] = 1818,
  [SMALL_STATE(143)] = 1822,
  [SMALL_STATE(144)] = 1826,
  [SMALL_STATE(145)] = 1830,
  [SMALL_STATE(146)] = 1834,
  [SMALL_STATE(147)] = 1838,
  [SMALL_STATE(148)] = 1842,
  [SMALL_STATE(149)] = 1846,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2, 0, 0), SHIFT_REPEAT(83),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2, 0, 0), SHIFT_REPEAT(37),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2, 0, 0), SHIFT_REPEAT(71),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2, 0, 0), SHIFT_REPEAT(96),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2, 0, 0), SHIFT_REPEAT(35),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_def_body_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_def_body_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_def_body_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_def_body_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_def_body_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(108),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use, 5, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_name, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pkg, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ext, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_body, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const, 6, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_body, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 5, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ext, 5, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0), SHIFT_REPEAT(129),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var, 6, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var, 6, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_statement, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_statement, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_statement, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_statement, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char, 3, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_arguments, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_arguments, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var, 4, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var, 4, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return, 4, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 4, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reassign, 4, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reassign, 4, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_arguments, 4, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var, 5, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var, 5, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var, 7, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var, 7, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_linker_option_repeat1, 2, 0, 0),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_linker_option_repeat1, 2, 0, 0), SHIFT_REPEAT(149),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [210] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_parameters, 3, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary, 2, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_parameters, 2, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_parameters, 4, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_def_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_def_parameters_repeat1, 2, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_return_repeat1, 2, 0, 0),
  [285] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_return_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [290] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_arguments_repeat1, 2, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [297] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(125),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_linker_option, 3, 0, 0),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_platform, 2, 0, 0),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_linker_option, 4, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [324] = {.entry = {.count = 1, .reusable = false}}, SHIFT(145),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2, 0, 0),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 3, 0, 0),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [350] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_name, 3, 0, 0),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [360] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 0),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [366] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 0),
  [368] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lucy(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lucy",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
